name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  schedule:
    - cron: "0 23 * * 0"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  lint:
    name: Lint
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1
      - id: setup
        uses: "oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6" # v2.2.0
        with:
          bun-version-file: "package.json"
      - run: "bun install --frozen-lockfile"
      - run: "bun run lint"

  format:
    name: Format
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1
      - id: setup
        uses: "oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6" # v2.2.0
        with:
          bun-version-file: "package.json"
      - run: "bun install --frozen-lockfile"
      - run: "bun run format"
